In [1]:
!pip install pandas





[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!python -m pip install --upgrade pip


  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\python311\\lib\\site-packages\\pip-22.3.1.dist-info\\entry_points.txt'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install gspread

  Using cached gspread-5.12.0-py3-none-any.whl (48 kB)



[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
!pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
!pip install matplotlib


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import warnings
import gspread
warnings.filterwarnings('ignore')

In [7]:
gc = gspread.service_account(filename = "C:\Data Science\Linear_Regression\linear-regression-404916-8d9c449085dc.json")

In [8]:
sheet = gc.open_by_url("https://docs.google.com/spreadsheets/d/1u-_oJRDYIF0TYfWUSuDhzflyImUINMokIpLo5jiFzcQ/edit?usp=sharing")

In [9]:
ws = sheet.worksheet('Sheet1')

In [13]:
df = pd.DataFrame(ws.get_all_records())

In [14]:
df.head()

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50

In [15]:
df.shape

(7, 2)

In [16]:
x = df['Weight']
y = df['Price']

In [17]:
x.head()

0    2
1    4
2    5
3    3
4    6
Name: Weight, dtype: int64

In [18]:
y.head()

0    35
1    60
2    20
3    50
4    50
Name: Price, dtype: int64

# Task 1

Your objective is to manually compute the slope (M) and y-intercept (C) using
Ordinary Least Squares Linear Regression. Once determined, apply these values to
predict the price when the vegetable weight is 6.

In [19]:
mean_x = np.mean(x)

In [20]:
mean_x

4.571428571428571

In [21]:
mean_y = np.mean(y)

In [22]:
mean_y

47.142857142857146

In [23]:
dev_x = x - mean_x
dev_y = y - mean_y

In [24]:
dev_x.head()

0   -2.571429
1   -0.571429
2    0.428571
3   -1.571429
4    1.428571
Name: Weight, dtype: float64

In [25]:
dev_y.head()

0   -12.142857
1    12.857143
2   -27.142857
3     2.857143
4     2.857143
Name: Price, dtype: float64

## General Equation for Linear Regression:

## Y = M*X + C

## Slope, m = Σ((x - x̄) * (y - ȳ)) / Σ((x - x̄)^2) 

## Intercept, c = ȳ - m * x̄

In [26]:
m = np.sum(dev_x * dev_y) / np.sum(dev_x**2) 

In [27]:
m

2.620967741935484

In [28]:
c = mean_y - m*mean_x

In [29]:
c

35.16129032258065

In [30]:
print(f"Slope (m): {m}")
print(f"Intercept (c): {c}")

Slope (m): 2.620967741935484
Intercept (c): 35.16129032258065


In [31]:
new_x = float(input('Enter any value of weight: '))
pred1 = m*new_x + c
print('predicted price is: {price}'.format(price=pred1))

Enter any value of weight:  6


predicted price is: 50.88709677419355


In [32]:
df

Weight  Price
0       2     35
1       4     60
2       5     20
3       3     50
4       6     50
5       5     55
6       7     60

## Task 02:
Compute the residuals for each data point.

In [33]:
new_x = df['Weight']
pred1 = m*new_x + c
residuals = y-pred1
dic = {
    'Weight': new_x,
    'Price': y,
    'Predicted Price': pred1,
    'Residual': residuals
    
}
df3 = pd.DataFrame(dic)

In [35]:
residuals

0    -5.403226
1    14.354839
2   -28.266129
3     6.975806
4    -0.887097
5     6.733871
6     6.491935
dtype: float64

In [36]:
df3

Weight  Price  Predicted Price   Residual
0       2     35        40.403226  -5.403226
1       4     60        45.645161  14.354839
2       5     20        48.266129 -28.266129
3       3     50        43.024194   6.975806
4       6     50        50.887097  -0.887097
5       5     55        48.266129   6.733871
6       7     60        53.508065   6.491935

# mean squared error


In [37]:
df3.shape

(7, 4)

In [38]:
len(residuals)

7

In [39]:
squared_residual = [residual**2 for residual in residuals]

In [40]:
mse_manual = sum(squared_residual)/len(squared_residual)

In [41]:
mse_manual

167.30990783410135

# mean absolute error

In [42]:
absolute_differences = abs(residuals)

In [43]:
absolute_differences

0     5.403226
1    14.354839
2    28.266129
3     6.975806
4     0.887097
5     6.733871
6     6.491935
dtype: float64

In [44]:
mae = sum(absolute_differences)/ len(absolute_differences)

In [45]:
mae

9.87327188940092

# Predicting Using Sklearn

In [46]:
!pip install sklearn


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [47]:
!python -m pip install --upgrade pip



  Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:


ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\python311\\lib\\site-packages\\pip-22.3.1.dist-info\\entry_points.txt'
Consider using the `--user` option or check the permissions.


[notice] A new release of pip available: 22.3.1 -> 23.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [48]:
from sklearn.linear_model import LinearRegression 

In [49]:
reg = LinearRegression()

In [50]:
reg.fit(df[['Weight']], y)

LinearRegression()

In [51]:
reg.coef_

array([2.62096774])

In [52]:
reg.intercept_

35.16129032258065

In [53]:
reg.predict([[6]])

array([50.88709677])

In [54]:
x = df.drop('Price', axis = 1)
y = df[['Price']]

In [55]:
reg.fit(x,y)

LinearRegression()

In [56]:
reg.predict(x)

array([[40.40322581],
       [45.64516129],
       [48.26612903],
       [43.02419355],
       [50.88709677],
       [48.26612903],
       [53.50806452]])

In [57]:
y['predicted_price'] =  reg.predict(x)

In [58]:
y

Price  predicted_price
0     35        40.403226
1     60        45.645161
2     20        48.266129
3     50        43.024194
4     50        50.887097
5     55        48.266129
6     60        53.508065

In [59]:
y['residuals'] = y['Price'] - y['predicted_price']


In [60]:
y

Price  predicted_price  residuals
0     35        40.403226  -5.403226
1     60        45.645161  14.354839
2     20        48.266129 -28.266129
3     50        43.024194   6.975806
4     50        50.887097  -0.887097
5     55        48.266129   6.733871
6     60        53.508065   6.491935

In [61]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [62]:
mse = mean_squared_error(y['Price'], reg.predict(x))

In [63]:
mse


167.30990783410135

In [64]:
mean_absolute_error(y['Price'], reg.predict(x))

9.87327188940092